//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessManagmentSystemEntities : DbContext
    {
        public MessManagmentSystemEntities()
            : base("name=MessManagmentSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AttendenceManager> AttendenceManagers { get; set; }
        public DbSet<Clerk> Clerks { get; set; }
        public DbSet<Meal> Meals { get; set; }
        public DbSet<MessRecord> MessRecords { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<Breakfast> Breakfasts { get; set; }
        public DbSet<Dinner> Dinners { get; set; }
        public DbSet<Launch> Launches { get; set; }
        public DbSet<MonthlyBill> MonthlyBills { get; set; }
    }
}
