//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessRecord
    {
        public string Month { get; set; }
        public string Expense { get; set; }
        public string Collection { get; set; }
        public string Balance { get; set; }
    }
}
