//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyBill
    {
        public int SerialNumber { get; set; }
        public string Month { get; set; }
        public string Name { get; set; }
        public string Room { get; set; }
        public string Bill { get; set; }
        public string UnitRate { get; set; }
        public string Total { get; set; }
        public string Recieved { get; set; }
    }
}
