//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string RegistrationNumber { get; set; }
        public string Name { get; set; }
        public string Room { get; set; }
        public string JoinDate { get; set; }
        public string LeaveDate { get; set; }
    }
}
